### ISSUE TITLE
Build issue in iOS when updating from 8.0.18 to 8.3.3

### ISSUE THREAD

**Issue by rollsroyc3** [Instabug/Instabug-React-Native#296]
### Steps to Reproduce the Problem
Update from 8.0.18 to 8.3.3

### Expected Behavior
Build as normal

### Actual Behavior
Get build error:

`/usr/local/lib/node_modules/instabug-reactnative/ios/RNInstabug/InstabugReactBridge.m:729:39: use of undeclared identifier 'IBGUserStepsModeEnable'; did you mean 'IBGUserStepsModeDisable'?`

Opening up the project in XCode and building I get a similar error:

https://www.dropbox.com/s/homhegyf73djzx5/Screenshot%202019-06-03%2011.56.44.png?dl=0

### SDK Version

"instabug-reactnative": "^8.3.3",

### React Native, iOS and Android Versions
"react-native": "^0.59.4",

**Comment by rollsroyc3** [comment]
Searching for this error I came across this

https://github.com/facebook/react-native-fbsdk/issues/533

which seems similar to my situation since I recently updated to .59

**Comment by hohien** [comment]
I get the same error, I solve it by go to the RCT_ENUM_CONVERTER and add IBGUserStepsModeEnable, It runs now. But that is not the right way to do

**Comment by salmamali** [comment]
Duplicate of #297
