### ISSUE TITLE
React Native 0.60 Android Compile Issues

### ISSUE THREAD

**Issue by Jaraujo6** [Instabug/Instabug-React-Native#321]
### Steps to Reproduce the Problem
run ```react-native run-android```

### Expected Behavior
app runs

### Actual Behavior
Compile error:
```
> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
135 actionable tasks: 3 executed, 132 up-to-date
/home/path-to-app/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:71: error: cannot find symbol
                new RNInstabugReactnativePackage.Builder("YOUR_ANDROID_APPLICATION_TOKEN",MainApplication.this)
                                                                                          ^
  symbol:   class MainApplication
  location: class PackageList
Note: /path-to-app/android/app/src/main/java/com/app/MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Instabug integration code

```
// the new api for manually linking packages in RN 0.60
packages.add(new RNInstabugReactnativePackage.Builder("Token",MainApplication.this)
            .setInvocationEvent("button")
            .setPrimaryColor("#1D82DC")
            .setFloatingEdge("left")
            .setFloatingButtonOffsetFromTop(250)
            .build());
```
### SDK Version

8.4.2

### React Native, iOS and Android Versions
RN 0.60.0
```
//gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```

**Comment by alyezz** [comment]
@Jaraujo6 we just release v8.5.0 which supports React Native 0.60. You can check out the migration guide [here](https://github.com/Instabug/Instabug-React-Native/blob/master/README.md#updating-to-version-85)

**Comment by HeshamMegid** [comment]
Closing this for now. @Jaraujo6 feel free to reopen if you're having any issues with v8.5 on React Native 0.60

**Comment by Jaraujo6** [comment]
It works with android/RN 0.60 with no issues. Thanks guys!
