### ISSUE TITLE
setUserEmail, setUserName, setUserStepsEnabled now missing in 8.1

### ISSUE THREAD

**Issue by plowman** [Instabug/Instabug-React-Native#255]
Hey there, I'm seeing lots of method calls that worked in 8.0 no longer work in 8.1. Was there some kind of purge that isn't documented in the [migration guide](https://docs.instabug.com/docs/react-native-sdk-8-1-migration-guide)?

For example, `setUserEmail()`, `setUserName()`, `setUserStepsEnabled()`, etc. were all in 8.0 but seem to have been removed.

If these are actually removed, it would be great if `index.d.ts` was updated to reflect which methods are actually callable still. It would also be nice if these changes were listed in the 8.1 migration steps, since I'm a little surprised there are so many breaking changes in a minor version bump release.

Thanks for your help!

### Steps to Reproduce the Problem
1. call `Instabug.setUserEmail("cool@beans.biz")` from anywhere

### Expected Behavior
* It should work.

### Actual Behavior
* An error is thrown:
```
TypeError: Instabug.setUserEmail is not a function
```

### SDK Version
8.1.3

### React Native, iOS and Android Versions
* RN 0.57.5
* iOS 12.1

**Comment by HeshamMegid** [comment]
@plowman those APIs have been deprecated for a few versions. In 8.1 we removed all APIs that have been deprecated in 8.0 and earlier versions. Please check the [8.0 migration guide](https://docs.instabug.com/v8.0/docs/react-native-migration-guide) for the deprecated APIs.

For the particular APIs you've mentioned, please use `identifyUserWithEmail()` instead of `identifyUserWithEmail()` and `setUserEmail()`. For user steps, please use `setTrackUserSteps()`.

`index.d.ts` is currently out of sync with some API changes in the latest version, sorry about that. We're working on updating it now.

**Comment by HeshamMegid** [comment]
@plowman the updated `index.d.ts` is available in 8.1.4.

Please let me know if you have any other questions about the API changes.

**Comment by plowman** [comment]
Thanks for making these changes, @HeshamMegid! This will make it much easier for everyone else who didn't realize those methods were deprecated.
